{% set name = "sphinx-material" %}
{% set dunder_name = name.replace("-", "_") %}
{% set version = "0.0.30" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ dunder_name }}/{{ dunder_name }}-{{ version }}.tar.gz
  sha256: a12864f832d792fd445e920c61c82f3c51233eaa652741d91bb20d7c38ab2a82

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3,<4
  run:
    - beautifulsoup4
    - css-html-js-minify
    - lxml
    - python >=3,<4
    - python-slugify
    - setuptools
    - slugify
    - sphinx >=2.0

test:
  imports:
    - sphinx_material

about:
  home: https://github.com/bashtage/sphinx-material
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: Material sphinx theme
  doc_url: https://pypi.org/project/sphinx-material/#description
  dev_url: https://github.com/bashtage/sphinx-material

extra:
  recipe-maintainers:
    - ndmaxar
    - oblute
    - rluria14
